# Generated by Django 4.0.4 on 2022-04-30 16:33

import cpf_field.models
from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=30)),
                ('nome', models.CharField(max_length=30)),
                ('grupo', models.PositiveIntegerField()),
                ('nome_do_grupo', models.CharField(max_length=30)),
                ('cpf', cpf_field.models.CPFField(max_length=14, verbose_name='cpf')),
                ('telefone', phone_field.models.PhoneField(blank=True, help_text='celular', max_length=31)),
                ('data_Nascto', models.DateField()),
                ('endereço', models.CharField(max_length=50)),
            ],
        ),
    ]
